### ISSUE TITLE
大佬 缺少文件requirements.txt呀

### ISSUE THREAD

**Issue by July7777777** [DeepFog-ORG/LyricAI#1]
大佬 缺少文件requirements.txt呀，麻烦提供下依赖文件  感谢

**Comment by DeepFog-ORG** [comment]
你好，本库是早期为测试OpenAI的ChatGPT所设置的，有许多阙漏请见谅。
requirements.txt 依赖清单如下

openai>=0.10.0
requests>=2.25.1
